# -*- coding: utf-8 -*-
"""Intrusion detection system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rFP9fF-4qosGDcbvHE6qbMMdznMj_ml
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/

import zipfile
import os

# Define file paths
zip_path = "/content/drive/MyDrive/archive (1).zip"  # Change this if needed
extract_path = "/content/NSL-KDD"

# Extract ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

!ls /content/NSL-KDD

import pandas as pd

# Define dataset path
data_path = "/content/NSL-KDD/KDDTrain+.txt"  # Change this if needed

# Load dataset
columns = [
    "duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land", "wrong_fragment",
    "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised", "root_shell", "su_attempted",
    "num_root", "num_file_creations", "num_shells", "num_access_files", "num_outbound_cmds",
    "is_host_login", "is_guest_login", "count", "srv_count", "serror_rate", "srv_serror_rate",
    "rerror_rate", "srv_rerror_rate", "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate",
    "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate", "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
    "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate", "label"
]

df = pd.read_csv(data_path, names=columns)

# Display dataset info
print(df.head())
print("✅ Data Loaded Successfully!")

#Deep learning models require numerical input, so we convert categorical columns (like protocol_type, service, etc.) into numbers.
from sklearn.preprocessing import LabelEncoder

# Convert categorical variables to numeric
categorical_cols = ["protocol_type", "service", "flag", "label"]

for col in categorical_cols:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])

print(df.head())
print("✅ Categorical Variables Encoded!")

from sklearn.model_selection import train_test_split
import numpy as np

# Split features (X) and labels (y)
X = df.drop(columns=["label"])  # Input Features
y = df["label"]  # Target Labels

# Normalize Data (Scale Features)
X = (X - X.min()) / (X.max() - X.min())

# Split into 80% Training and 20% Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("✅ Data Split into Training & Testing!")
print(f"Training Samples: {X_train.shape[0]}, Testing Samples: {X_test.shape[0]}")

print(df.dtypes)

print(df.head())  # See the first few rows
print(df.info())  # Check data types
print(df.isnull().sum())  # Check missing values

df['duration'] = df['dst_host_srv_rerror_rate'].astype('category').cat.codes

df = df.apply(pd.to_numeric, errors='coerce')  # Converts all columns to numeric, replacing errors with NaN
df.fillna(0, inplace=True)  # Replace NaN with 0

from sklearn.model_selection import train_test_split
import numpy as np

# Split features (X) and labels (y)
X = df.drop(columns=["label"])  # Input Features
y = df["label"]  # Target Labels

# Normalize Data (Scale Features)
X = (X - X.min()) / (X.max() - X.min())

# Split into 80% Training and 20% Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("✅ Data Split into Training & Testing!")
print(f"Training Samples: {X_train.shape[0]}, Testing Samples: {X_test.shape[0]}")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

# Define Deep ANN Model
dann_model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.4),

    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Output Layer for Binary Classification
])

# Compile Model
dann_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Model Summary
dann_model.summary()

# Train Model
dann_model.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test))

print("✅ Deep ANN Model Training Completed!")

from tensorflow.keras.layers import Conv1D, Flatten, MaxPooling1D

# Define Deep CNN Model
dcnn_model = Sequential([
    Conv1D(128, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    Conv1D(64, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    Conv1D(32, kernel_size=3, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile Model
dcnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Model Summary
dcnn_model.summary()

# Reshape data for CNN
X_train_cnn = np.expand_dims(X_train, axis=-1)
X_test_cnn = np.expand_dims(X_test, axis=-1)

# Train Model
dcnn_model.fit(X_train_cnn, y_train, epochs=20, batch_size=64, validation_data=(X_test_cnn, y_test))

print("✅ Deep CNN Model Training Completed!")









from tensorflow.keras.layers import LSTM

# Define Deep LSTM Model
dlstm_model = Sequential([
    LSTM(128, return_sequences=True, input_shape=(X_train.shape[1], 1)),
    Dropout(0.3),

    LSTM(64, return_sequences=True),
    Dropout(0.3),

    LSTM(32),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile Model
dlstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Model Summary
dlstm_model.summary()

# Reshape Data for LSTM
X_train_lstm = np.expand_dims(X_train, axis=-1)
X_test_lstm = np.expand_dims(X_test, axis=-1)

# Train Model
dlstm_model.fit(X_train_lstm, y_train, epochs=20, batch_size=64, validation_data=(X_test_lstm, y_test))

print("✅ Deep LSTM Model Training Completed!")

# Evaluate Deep ANN Model
dann_loss, dann_acc = dann_model.evaluate(X_test, y_test)
print(f"🔥 Deep ANN Accuracy: {dann_acc:.4f}")

# Evaluate Deep CNN Model
dcnn_loss, dcnn_acc = dcnn_model.evaluate(X_test_cnn, y_test)
print(f"🔥 Deep CNN Accuracy: {dcnn_acc:.4f}")

# Evaluate Deep LSTM Model
dlstm_loss, dlstm_acc = dlstm_model.evaluate(X_test_lstm, y_test)
print(f"🔥 Deep LSTM Accuracy: {dlstm_acc:.4f}")

from sklearn.metrics import classification_report  # ✅ Correct Import

# Predictions for each model (thresholding at 0.5)
y_pred_dann = (dann_model.predict(X_test) > 0.5).astype("int32")
y_pred_dcnn = (dcnn_model.predict(X_test_cnn) > 0.5).astype("int32")
y_pred_dlstm = (dlstm_model.predict(X_test_lstm) > 0.5).astype("int32")

# Print Classification Reports
print("\n🔥 Deep ANN Model Classification Report:\n", classification_report(y_test, y_pred_dann))
print("\n🔥 Deep CNN Model Classification Report:\n", classification_report(y_test, y_pred_dcnn))
print("\n🔥 Deep LSTM Model Classification Report:\n", classification_report(y_test, y_pred_dlstm))

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Assuming you have test labels (y_test) and predicted labels (y_pred)
y_pred = dann_model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)  # Convert probabilities to class labels (for multi-class classification)

# Generate and print evaluation metrics
print("✅ Model Evaluation Results:\n")

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"🔹 Accuracy: {accuracy:.4f}")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred_classes)
print("\n🔹 Confusion Matrix:")
print(conf_matrix)

# Classification Report (Precision, Recall, F1-score)
class_report = classification_report(y_test, y_pred_classes)
print("\n🔹 Classification Report:")
print(class_report)